export const LOADING = "LOADING"
export const SUCCESS = "SUCCESS"
export const ERROR = "ERROR"

//DASHBOARD:====
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GETCOMPANY_DASHBOARD = "GETCOMPANY_DASHBOARD";
export const GETCOMPANY_LINECHART = "GETCOMPANY_LINECHART";
export const GET_PIECHART = "GET_PIECHART";
export const GET_LINECHART = "GET_LINECHART";
export const GET_BARCHART = "GET_BARCHART";
export const GET_APPLIED = "GET_APPLIED";
export const GET_REPORTS = "GET_REPORTS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";


// CATEGORIES:=====
export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const RESET_STATUS = "RESET_STATUS";

// CITIES:=====
export const ALL_CITIES = "ALL_CITIES";
export const GET_CITY = "GET_CITY";
export const GETCOUNTRY_CITY = "GETCOUNTRY_CITY"
export const UPDATE_CITY = "UPDATE_CITY";
export const CITY_STATUS = "CITY_STATUS";
export const DELETE_CITY = "DELETE_CITY";
export const CREATE_CITY = "CREATE_CITY";

// JOBS:=====
export const ALL_JOBS = "ALL_JOBS";
export const GET_JOBS = "GET_JOBS";
export const GET_JOB = "GET_JOB";
export const RECENT_JOB = "RECENT_JOB";
export const GETCATEGORY_JOB = "GETCATEGORY_JOB";
export const GETCOUNTRY_JOB = "GETCOUNTRY_JOB";
export const GETCITY_JOB = "GETCITY_JOB";
export const GETCOMPANY_JOB = "GETCOMPANY_JOB";
export const CREATE_JOB = "CREATE_JOB";
export const JOBS_STATUS = "CITY_STATUS";

export const UPDATE_JOB = "UPDATE_JOB";
export const DELETE_JOB = "DELETE_JOB";


// COMPANIES:=====
export const ALL_COMPANIES = "ALL_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const COMPANY_STATUS = "CITY_STATUS";


// COUNTRIES:=====
export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const COUNTRY_STATUS = "CITY_STATUS";


// PLANS:=====
export const ALL_PLANS = "ALL_PLANS";
export const GET_PLAN = "GET_PLAN";
export const UPDATE_PLAN = "UPDATE_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
export const CREATE_PLAN = "CREATE_PLAN";
export const PLANS_STATUS = "CITY_STATUS";


// REPORTS:=====
export const ALL_REPORTS = "ALL_REPORTS";
export const GET_REPORT = "GET_REPORT";
export const UPDATE_REPORT = "UPDATE_REPORT";
export const DELETE_REPORT = "DELETE_REPORT";
export const CREATE_REPORT = "CREATE_REPORT";
export const REPORT_STATUS = "CITY_STATUS";

// SEEKERS:=====
export const ALL_SEEKERS = "ALL_SEEKERS";
export const RECOMMENDED_SEEKER = "RECOMMENDED_SEEKER";
export const GET_SEEKER = "GET_SEEKER";
export const UPDATE_SEEKER = "UPDATE_SEEKER";
export const DELETE_SEEKER = "DELETE_SEEKER";
export const CREATE_SEEKER = "CREATE_SEEKER";
export const SEEKER_STATUS = "CITY_STATUS";

//coverLetter
export const GET_COVER_BY_USER = "GET_COVER_BY_USER";

//CV : ====
export const CVBY_USER = "CVBY_USER"

// TAGS:=====
export const ALL_TAGS = "ALL_TAGS";
export const GET_TAG = "GET_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const CREATE_TAG = "CREATE_TAG";
export const TAG_STATUS = "CITY_STATUS";



// TRANSACTIONS:=====
export const ALL_TRANSACTIONS = "ALL_TRANSACTIONS";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const TRANSACTION_STATUS = "CITY_STATUS";


// USERS:=====
export const ALL_USERS = "ALL_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const CREATE_USER = "CREATE_USER";
export const USER_STATUS = "CITY_STATUS";


// APPLIEDUSERS:=====
export const ALL_APPLIEDUSERS = "ALL_APPLIEDUSERS";
export const GET_APPLIEDUSER = "GET_APPLIEDUSER";
export const GETJOB_APPLIEDUSER = "GETJOB_APPLIEDUSER";
export const GETCOMPANY_APPLIEDUSER = "GETCOMPANY_APPLIEDUSER";
export const UPDATE_APPLIEDUSER = "UPDATE_APPLIEDUSER";
export const DELETE_APPLIEDUSER = "DELETE_APPLIEDUSER";
export const CREATE_APPLIEDUSER = "CREATE_APPLIEDUSER";
export const APPLIEDUSER_STATUS = "CITY_STATUS";

// Interactions: ========
export const ALL_INTERACTIONS = "ALL_INTERACTIONS";
export const GET_INTERACTIONS = "GET_INTERACTIONS";
export const GETCOMPANY_INTERACTIONS = "GETCOMPANY_INTERACTIONS";

//Payment
export const ALL_PAYMENT = "ALL_PAYMENT";
export const GET_STRIPE = "GET_STRIPE";
export const GET_PAYPAL = "GET_PAYPAL";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const UPDATE_PAYPAL = "UPDATE_PAYPAL";
export const UPDATE_STRIPE = "UPDATE_STRIPE";

//Offers
export const ALL_OFFERS = "ALL_OFFERS";
export const GET_OFFERS = "GET_OFFERS";
export const OFFERS_BY_COMPANY = "OFFERS_BY_COMPANY";


//JobsApi
export const ALL_JOBS_API = "ALL_JOBS_API";

//JobsBank
export const ALL_JOBBANKS = "ALL_JOBBANKS";
export const CREATE_JOBBANK = "CREATE_JOBBANK";
export const UPDATE_JOBBANK = "UPDATE_JOBBANK";
export const DELETE_JOBBANK = "DELETE_JOBBANK";

export const SESSION_PROVIDER_LOGIN = "JOBS_AU_PROVIDER_LOGIN"
export const SESSION_ADMIN_LOGIN = "JOBS_AU_ADMIN_LOGIN"
export const SESSION_ADMIN_USER = "JOBS_AU_ADMIN_USER"
export const SESSION_ADMIN_ID = "JOBS_AU_ADMIN_ID"
export const SESSION_ADMIN_TYPE = "JOBS_AU_ADMIN_TYPE"
export const SESSION_PROVIDER = "JOBS_AU_PROVIDER"
export const SESSION_USER = "JOBS_AU_USER"
export const SESSION_PROVIDER_ID = "JOBS_AU_PROVIDER_ID"
export const SESSION_PROVIDER_TYPE = "JOBS_AU_PROVIDER_TYPE"



